name: egyoutfit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite: ^1.3.0
  intl: ^0.17.0
  conditional_builder: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.5
  webview_flutter: ^2.0.3
  smooth_page_indicator: ^0.2.0
  fluttertoast: ^8.0.3
  carousel_slider: ^3.0.0
  fluttericon: ^2.0.0
  animated_splash_screen: ^1.2.0
  http: ^0.13.4
  firebase_core: any
  firebase_core_web: any
  cloud_firestore: any
  firebase_auth: any
  image_picker: ^0.8.4+11
  firebase_storage: any
  firebase_storage_web: any
  dots_indicator: ^2.1.0
  awesome_dialog: ^2.2.1
  dropdown_button2: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700

    - family: myCart
      fonts:
        - asset: assets/fonts/myCart.ttf

    - family: myCart2
      fonts:
        - asset: assets/fonts/myCart2.ttf

    - family: myHome
      fonts:
        - asset: assets/fonts/myHome.ttf

    - family: myHeart
      fonts:
        - asset: assets/fonts/myHeart.ttf

    - family: myPerson
      fonts:
        - asset: assets/fonts/myPerson.ttf

    - family: myOffers
      fonts:
        - asset: assets/fonts/myOffers.ttf
